/**
 * The half of `capture.mjs` that does not need a browser.
 *
 * `captureSite()` itself is only tested through `run.test.mjs`, with a fake in
 * its place: launching Chromium against the live web inside a unit suite would
 * make the suite as reliable as somebody else's uptime. What IS worth pinning
 * down here is `extractPalette()` — it is a pure function from pixels to hex,
 * and every rule it enforces is a judgement call that a future edit could
 * quietly reverse.
 *
 * Every fixture is generated by sharp rather than committed, so the expected
 * colours are arithmetic rather than "whatever that PNG happens to contain".
 */

import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";

import sharp from "sharp";

import {
  MAX_SHOT_PX,
  captureWithFirecrawl,
  extractPalette,
  scrollThroughPage,
} from "./capture.mjs";

/**
 * A PNG built from horizontal bands, top to bottom.
 *
 * @param {readonly { colour: [number, number, number], rows: number }[]} bands
 * @param {number} [width]
 * @returns {Promise<Buffer>}
 */
async function bandedPng(bands, width = 400) {
  const height = bands.reduce((total, band) => total + band.rows, 0);
  const pixels = Buffer.alloc(width * height * 3);

  let offset = 0;
  for (const { colour, rows } of bands) {
    for (let i = 0; i < rows * width; i += 1) {
      pixels[offset] = colour[0];
      pixels[offset + 1] = colour[1];
      pixels[offset + 2] = colour[2];
      offset += 3;
    }
  }

  return sharp(pixels, { raw: { width, height, channels: 3 } }).png().toBuffer();
}

const WHITE = /** @type {[number, number, number]} */ ([255, 255, 255]);
const BLACK = /** @type {[number, number, number]} */ ([0, 0, 0]);
const RED = /** @type {[number, number, number]} */ ([220, 40, 40]);
const BLUE = /** @type {[number, number, number]} */ ([40, 70, 220]);
const GREEN = /** @type {[number, number, number]} */ ([30, 160, 90]);

test("a flat colour comes back as one hex string", async () => {
  const png = await bandedPng([{ colour: RED, rows: 200 }]);

  assert.deepEqual(await extractPalette(png), ["#dc2828"]);
});

test("colours come back most-used first", async () => {
  const png = await bandedPng([
    { colour: RED, rows: 40 },
    { colour: BLUE, rows: 120 },
    { colour: GREEN, rows: 80 },
  ]);

  assert.deepEqual(await extractPalette(png), ["#2846dc", "#1ea05a", "#dc2828"]);
});

test("a white margin around a coloured page does not take a slot", async () => {
  // 10% white: present, but nowhere near the share an extreme has to own.
  const png = await bandedPng([
    { colour: WHITE, rows: 20 },
    { colour: RED, rows: 100 },
    { colour: BLUE, rows: 80 },
  ]);

  const palette = await extractPalette(png);

  assert.deepEqual(palette, ["#dc2828", "#2846dc"]);
});

test("a page that really is white says so", async () => {
  // 80% white. This is not a margin, it is the design.
  const png = await bandedPng([
    { colour: WHITE, rows: 160 },
    { colour: RED, rows: 40 },
  ]);

  assert.deepEqual(await extractPalette(png), ["#ffffff", "#dc2828"]);
});

test("a dark site keeps its black", async () => {
  const png = await bandedPng([
    { colour: BLACK, rows: 150 },
    { colour: GREEN, rows: 50 },
  ]);

  assert.deepEqual(await extractPalette(png), ["#000000", "#1ea05a"]);
});

test("two shades of the same colour collapse into one swatch", async () => {
  const near = /** @type {[number, number, number]} */ ([224, 46, 46]);
  const png = await bandedPng([
    { colour: RED, rows: 100 },
    { colour: near, rows: 100 },
  ]);

  const palette = await extractPalette(png);

  assert.equal(palette.length, 1, "a 4-per-channel difference is not a second colour");
});

test("the palette is capped, and the cap is a parameter", async () => {
  const png = await bandedPng([
    { colour: RED, rows: 60 },
    { colour: BLUE, rows: 50 },
    { colour: GREEN, rows: 40 },
    { colour: [200, 160, 20], rows: 30 },
    { colour: [120, 30, 190], rows: 20 },
    { colour: [20, 190, 200], rows: 10 },
    { colour: [190, 90, 160], rows: 8 },
    { colour: [90, 120, 30], rows: 6 },
  ]);

  assert.equal((await extractPalette(png)).length, 6, "the default is six");
  assert.equal((await extractPalette(png, { size: 3 })).length, 3);
});

test("every colour is a lowercase six-digit hex string", async () => {
  const png = await bandedPng([
    { colour: [5, 10, 250], rows: 100 },
    { colour: [250, 250, 5], rows: 100 },
  ]);

  for (const colour of await extractPalette(png)) {
    assert.match(colour, /^#[0-9a-f]{6}$/, `${colour} is not a parseable hex colour`);
  }
});

test("a page of nothing but near-white still yields a colour", async () => {
  // Everything here is filtered out by the extreme rule, so the fallback pass is
  // the only thing standing between this page and an empty palette.
  const png = await bandedPng([
    { colour: [252, 252, 252], rows: 100 },
    { colour: [246, 244, 240], rows: 30 },
  ]);

  const palette = await extractPalette(png);

  assert.ok(palette.length >= 1, "an empty palette is never the honest answer");
  assert.match(palette[0], /^#[0-9a-f]{6}$/);
});

/* ---------------------------------------------------------------------------
   The Firecrawl capturer
   --------------------------------------------------------------------------- */

/**
 * The other half of `capture.mjs` that needs no browser. `captureWithFirecrawl`
 * takes its client as an argument, so the whole encode path — clip, palette,
 * WebP, file on disk — runs here for real against real sharp, with only the
 * network stubbed. That is the half worth testing: `run.test.mjs` replaces this
 * function wholesale, so without these two the sharp side would never execute.
 *
 * @param {import("node:test").TestContext} t
 */
async function scratch(t) {
  const dir = await mkdtemp(path.join(tmpdir(), "capture-test-"));
  t.after(() => rm(dir, { recursive: true, force: true }));
  return dir;
}

/** @param {Buffer} png @returns {any} A client that answers with this PNG. */
const clientReturning = (png) => ({
  screenshotFullPage: async () => png,
  scrapeMarkdown: async () => "",
});

test("a Firecrawl shot lands as a WebP with a palette read off it", async (t) => {
  const outDir = await scratch(t);
  const png = await bandedPng([
    { colour: BLUE, rows: 300 },
    { colour: RED, rows: 100 },
  ]);

  const result = await captureWithFirecrawl({
    url: "https://fortress.example",
    slug: "fortress",
    client: clientReturning(png),
    outDir,
  });

  assert.equal(result.shot, path.join(outDir, "fortress.webp"));
  assert.deepEqual(result.palette, ["#2846dc", "#dc2828"], "the same binning as any other shot");

  const written = await sharp(result.shot).metadata();
  assert.equal(written.format, "webp", "and the same encoder, so the gallery cannot tell them apart");
});

test("a Firecrawl shot too tall to keep is clipped to the same ceiling", async (t) => {
  const outDir = await scratch(t);
  /** @type {string[]} */
  const lines = [];

  // Firecrawl has no clip parameter, so the whole scroll arrives and the trim
  // has to happen locally. Narrow on purpose: the height is the point.
  const png = await bandedPng([{ colour: RED, rows: MAX_SHOT_PX + 500 }], 8);

  await captureWithFirecrawl({
    url: "https://endless.example",
    slug: "endless",
    client: clientReturning(png),
    outDir,
    log: (line) => lines.push(line),
  });

  const written = await sharp(path.join(outDir, "endless.webp")).metadata();
  assert.equal(written.height, MAX_SHOT_PX, "the ceiling is the ceiling whoever took the picture");
  assert.deepEqual(lines, [`capture: endless is ${MAX_SHOT_PX + 500}px tall, clipped to the first ${MAX_SHOT_PX}px`]);
});

test("a slug that is not URL-safe is refused before anything is asked of Firecrawl", async (t) => {
  const outDir = await scratch(t);
  let asked = false;

  await assert.rejects(
    captureWithFirecrawl({
      url: "https://a.example",
      slug: "../../etc/passwd",
      outDir,
      client: {
        screenshotFullPage: async () => {
          asked = true;
          return Buffer.alloc(0);
        },
        scrapeMarkdown: async () => "",
      },
    }),
    /URL-safe slug/,
  );

  assert.equal(asked, false, "a slug is a filename before it is anything else");
});

/* ---------------------------------------------------------------------------
   The walk-down

   `scrollThroughPage` is the fix for a shot that came back as a correct hero
   over thousands of pixels of flat background: the page's lazy images and
   scroll-revealed sections were never asked to mount. It takes its page as a
   four-method object precisely so the walk can be checked without a browser —
   what matters is WHERE it goes and that it pauses once it gets there, and a
   fake answers that better than Chromium does.
   --------------------------------------------------------------------------- */

/**
 * A page that records the walk instead of performing it.
 *
 * @param {object} [options]
 * @param {number} [options.height]    Document height, or the first of them.
 * @param {number} [options.viewport]
 * @param {number} [options.growth]    Added to the height on every measurement.
 */
function fakePage({ height = 5_000, viewport = 900, growth = 0 } = {}) {
  /** @type {number[]} */
  const visited = [];
  /** @type {number[]} */
  const pauses = [];
  let measured = height;

  return {
    visited,
    pauses,
    scroller: {
      viewportHeight: async () => viewport,
      documentHeight: async () => {
        const now = measured;
        measured += growth;
        return now;
      },
      scrollTo: async (/** @type {number} */ y) => void visited.push(y),
      pause: async (/** @type {number} */ ms) => void pauses.push(ms),
    },
  };
}

test("the walk visits every screen of the page, a viewport at a time", async () => {
  const page = fakePage({ height: 4_000, viewport: 900 });

  const { steps } = await scrollThroughPage(page.scroller, { stepMs: 5, settleMs: 5 });

  // 0, 900, 1800, 2700, 3600 — then the bottom, then home.
  assert.deepEqual(
    page.visited,
    [0, 900, 1800, 2700, 3600, 4000, 0],
    "a screen skipped is a screen of content that never mounts",
  );
  assert.equal(steps, 5);
});

test("the walk pauses on every screen, which is the whole point of it", async () => {
  const page = fakePage({ height: 2_700, viewport: 900 });

  await scrollThroughPage(page.scroller, { stepMs: 150, settleMs: 1_000 });

  assert.deepEqual(
    page.pauses,
    [150, 150, 150, 1_000, 1_000],
    "three steps at the step pause, then the bottom and the top at the settle",
  );
});

test("the walk ends at the top, not wherever it finished", async () => {
  const page = fakePage({ height: 9_000 });

  await scrollThroughPage(page.scroller, { stepMs: 1, settleMs: 1 });

  assert.equal(
    page.visited.at(-1),
    0,
    "a sticky header photographed mid-page is the wrong picture of the top of the page",
  );
});

test("the walk stops at the clip ceiling instead of touring the whole page", async () => {
  const page = fakePage({ height: 60_000, viewport: 900 });

  const { depth } = await scrollThroughPage(page.scroller, { stepMs: 1, settleMs: 1 });

  assert.ok(
    depth <= MAX_SHOT_PX + 900,
    `nothing past the ceiling survives the clip, so ${depth} is time spent on discarded pixels`,
  );
  assert.ok(Math.max(...page.visited) <= MAX_SHOT_PX + 900);
});

test("a page shorter than one screen is one stop and no wasted steps", async () => {
  const page = fakePage({ height: 400, viewport: 900 });

  const { steps } = await scrollThroughPage(page.scroller, { stepMs: 1, settleMs: 1 });

  assert.equal(steps, 1, "the top still has to be visited; the second screen does not exist");
  assert.deepEqual(page.visited, [0, 400, 0]);
});

test("a page that grows every time it is measured is still bounded", async () => {
  // An infinite feed: every measurement reports a taller document than the last,
  // so the ceiling is never reached and only the step guard can end this.
  const page = fakePage({ height: 5_000, viewport: 900, growth: 5_000 });

  const { steps } = await scrollThroughPage(page.scroller, {
    stepMs: 1,
    settleMs: 1,
    maxSteps: 12,
  });

  assert.equal(steps, 12, "the guard is the only thing standing between this and the deadline");
});

test("a page reporting a zero-height viewport falls back to the shot viewport", async () => {
  const page = fakePage({ height: 3_000, viewport: 0 });

  const { steps } = await scrollThroughPage(page.scroller, {
    stepMs: 1,
    settleMs: 1,
    maxSteps: 200,
  });

  // Stepping by 1px would take 200 steps to cover 200px and burn the deadline.
  assert.deepEqual(page.visited, [0, 900, 1800, 2700, 3000, 0]);
  assert.equal(steps, 4);
});

test("transparency is composited onto white, not read as black", async () => {
  // A screenshot has no alpha, but a PNG with one must not turn a transparent
  // header into a bogus black swatch on its way through sharp.
  const png = await sharp({
    create: {
      width: 200,
      height: 200,
      channels: 4,
      background: { r: 220, g: 40, b: 40, alpha: 0 },
    },
  })
    .png()
    .toBuffer();

  assert.deepEqual(await extractPalette(png), ["#ffffff"]);
});
