/**
 * The half of `capture.mjs` that does not need a browser.
 *
 * `captureSite()` itself is only tested through `run.test.mjs`, with a fake in
 * its place: launching Chromium against the live web inside a unit suite would
 * make the suite as reliable as somebody else's uptime. What IS worth pinning
 * down here is `extractPalette()` — it is a pure function from pixels to hex,
 * and every rule it enforces is a judgement call that a future edit could
 * quietly reverse.
 *
 * Every fixture is generated by sharp rather than committed, so the expected
 * colours are arithmetic rather than "whatever that PNG happens to contain".
 */

import assert from "node:assert/strict";
import { access, mkdtemp, readFile, readdir, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";

import sharp from "sharp";

import {
  CHALLENGE_SELECTORS,
  CHALLENGE_SIGNATURES,
  CaptureBlockedError,
  DEFAULT_OUT_DIR,
  MAX_SHOT_PX,
  captureWithFirecrawl,
  extractPalette,
  matchChallenge,
  measureShot,
  scrollThroughPage,
  shotLooksBlank,
} from "./capture.mjs";

/**
 * A PNG built from horizontal bands, top to bottom.
 *
 * @param {readonly { colour: [number, number, number], rows: number }[]} bands
 * @param {number} [width]
 * @returns {Promise<Buffer>}
 */
async function bandedPng(bands, width = 400) {
  const height = bands.reduce((total, band) => total + band.rows, 0);
  const pixels = Buffer.alloc(width * height * 3);

  let offset = 0;
  for (const { colour, rows } of bands) {
    for (let i = 0; i < rows * width; i += 1) {
      pixels[offset] = colour[0];
      pixels[offset + 1] = colour[1];
      pixels[offset + 2] = colour[2];
      offset += 3;
    }
  }

  return sharp(pixels, { raw: { width, height, channels: 3 } }).png().toBuffer();
}

const WHITE = /** @type {[number, number, number]} */ ([255, 255, 255]);
const BLACK = /** @type {[number, number, number]} */ ([0, 0, 0]);
const RED = /** @type {[number, number, number]} */ ([220, 40, 40]);
const BLUE = /** @type {[number, number, number]} */ ([40, 70, 220]);
const GREEN = /** @type {[number, number, number]} */ ([30, 160, 90]);

test("a flat colour comes back as one hex string", async () => {
  const png = await bandedPng([{ colour: RED, rows: 200 }]);

  assert.deepEqual(await extractPalette(png), ["#dc2828"]);
});

test("colours come back most-used first", async () => {
  const png = await bandedPng([
    { colour: RED, rows: 40 },
    { colour: BLUE, rows: 120 },
    { colour: GREEN, rows: 80 },
  ]);

  assert.deepEqual(await extractPalette(png), ["#2846dc", "#1ea05a", "#dc2828"]);
});

test("a white margin around a coloured page does not take a slot", async () => {
  // 10% white: present, but nowhere near the share an extreme has to own.
  const png = await bandedPng([
    { colour: WHITE, rows: 20 },
    { colour: RED, rows: 100 },
    { colour: BLUE, rows: 80 },
  ]);

  const palette = await extractPalette(png);

  assert.deepEqual(palette, ["#dc2828", "#2846dc"]);
});

test("a page that really is white says so", async () => {
  // 80% white. This is not a margin, it is the design.
  const png = await bandedPng([
    { colour: WHITE, rows: 160 },
    { colour: RED, rows: 40 },
  ]);

  assert.deepEqual(await extractPalette(png), ["#ffffff", "#dc2828"]);
});

test("a dark site keeps its black", async () => {
  const png = await bandedPng([
    { colour: BLACK, rows: 150 },
    { colour: GREEN, rows: 50 },
  ]);

  assert.deepEqual(await extractPalette(png), ["#000000", "#1ea05a"]);
});

test("two shades of the same colour collapse into one swatch", async () => {
  const near = /** @type {[number, number, number]} */ ([224, 46, 46]);
  const png = await bandedPng([
    { colour: RED, rows: 100 },
    { colour: near, rows: 100 },
  ]);

  const palette = await extractPalette(png);

  assert.equal(palette.length, 1, "a 4-per-channel difference is not a second colour");
});

test("the palette is capped, and the cap is a parameter", async () => {
  const png = await bandedPng([
    { colour: RED, rows: 60 },
    { colour: BLUE, rows: 50 },
    { colour: GREEN, rows: 40 },
    { colour: [200, 160, 20], rows: 30 },
    { colour: [120, 30, 190], rows: 20 },
    { colour: [20, 190, 200], rows: 10 },
    { colour: [190, 90, 160], rows: 8 },
    { colour: [90, 120, 30], rows: 6 },
  ]);

  assert.equal((await extractPalette(png)).length, 6, "the default is six");
  assert.equal((await extractPalette(png, { size: 3 })).length, 3);
});

test("every colour is a lowercase six-digit hex string", async () => {
  const png = await bandedPng([
    { colour: [5, 10, 250], rows: 100 },
    { colour: [250, 250, 5], rows: 100 },
  ]);

  for (const colour of await extractPalette(png)) {
    assert.match(colour, /^#[0-9a-f]{6}$/, `${colour} is not a parseable hex colour`);
  }
});

test("a page of nothing but near-white still yields a colour", async () => {
  // Everything here is filtered out by the extreme rule, so the fallback pass is
  // the only thing standing between this page and an empty palette.
  const png = await bandedPng([
    { colour: [252, 252, 252], rows: 100 },
    { colour: [246, 244, 240], rows: 30 },
  ]);

  const palette = await extractPalette(png);

  assert.ok(palette.length >= 1, "an empty palette is never the honest answer");
  assert.match(palette[0], /^#[0-9a-f]{6}$/);
});

/* ---------------------------------------------------------------------------
   The Firecrawl capturer
   --------------------------------------------------------------------------- */

/**
 * The other half of `capture.mjs` that needs no browser. `captureWithFirecrawl`
 * takes its client as an argument, so the whole encode path — clip, palette,
 * WebP, file on disk — runs here for real against real sharp, with only the
 * network stubbed. That is the half worth testing: `run.test.mjs` replaces this
 * function wholesale, so without these two the sharp side would never execute.
 *
 * @param {import("node:test").TestContext} t
 */
async function scratch(t) {
  const dir = await mkdtemp(path.join(tmpdir(), "capture-test-"));
  t.after(() => rm(dir, { recursive: true, force: true }));
  return dir;
}

/** @param {Buffer} png @returns {any} A client that answers with this PNG. */
const clientReturning = (png) => ({
  screenshotFullPage: async () => png,
  scrapeMarkdown: async () => "",
});

test("a Firecrawl shot lands as a WebP with a palette read off it", async (t) => {
  const outDir = await scratch(t);
  const png = await bandedPng([
    { colour: BLUE, rows: 300 },
    { colour: RED, rows: 100 },
  ]);

  const result = await captureWithFirecrawl({
    url: "https://fortress.example",
    slug: "fortress",
    client: clientReturning(png),
    outDir,
  });

  assert.equal(result.shot, path.join(outDir, "fortress.webp"));
  assert.deepEqual(result.palette, ["#2846dc", "#dc2828"], "the same binning as any other shot");

  const written = await sharp(result.shot).metadata();
  assert.equal(written.format, "webp", "and the same encoder, so the gallery cannot tell them apart");
});

test("a Firecrawl shot too tall to keep is clipped to the same ceiling", async (t) => {
  const outDir = await scratch(t);
  /** @type {string[]} */
  const lines = [];

  // Firecrawl has no clip parameter, so the whole scroll arrives and the trim
  // has to happen locally. Narrow on purpose: the height is the point.
  //
  // Banded rather than one flat colour, because a flat colour is what the
  // blank-shot backstop exists to refuse — a single-hue image this tall is a
  // capture of nothing, and `finish` would rightly throw before the clip could
  // be checked. Two colours make it a page.
  const png = await bandedPng(
    Array.from({ length: 25 }, (_, band) => ({
      colour: band % 2 === 0 ? RED : BLUE,
      rows: (MAX_SHOT_PX + 500) / 25,
    })),
    8,
  );

  await captureWithFirecrawl({
    url: "https://endless.example",
    slug: "endless",
    client: clientReturning(png),
    outDir,
    log: (line) => lines.push(line),
  });

  const written = await sharp(path.join(outDir, "endless.webp")).metadata();
  assert.equal(written.height, MAX_SHOT_PX, "the ceiling is the ceiling whoever took the picture");
  assert.deepEqual(lines, [`capture: endless is ${MAX_SHOT_PX + 500}px tall, clipped to the first ${MAX_SHOT_PX}px`]);
});

test("a slug that is not URL-safe is refused before anything is asked of Firecrawl", async (t) => {
  const outDir = await scratch(t);
  let asked = false;

  await assert.rejects(
    captureWithFirecrawl({
      url: "https://a.example",
      slug: "../../etc/passwd",
      outDir,
      client: {
        screenshotFullPage: async () => {
          asked = true;
          return Buffer.alloc(0);
        },
        scrapeMarkdown: async () => "",
      },
    }),
    /URL-safe slug/,
  );

  assert.equal(asked, false, "a slug is a filename before it is anything else");
});

/* ---------------------------------------------------------------------------
   The walk-down

   `scrollThroughPage` is the fix for a shot that came back as a correct hero
   over thousands of pixels of flat background: the page's lazy images and
   scroll-revealed sections were never asked to mount. It takes its page as a
   four-method object precisely so the walk can be checked without a browser —
   what matters is WHERE it goes and that it pauses once it gets there, and a
   fake answers that better than Chromium does.
   --------------------------------------------------------------------------- */

/**
 * A page that records the walk instead of performing it.
 *
 * @param {object} [options]
 * @param {number} [options.height]    Document height, or the first of them.
 * @param {number} [options.viewport]
 * @param {number} [options.growth]    Added to the height on every measurement.
 */
function fakePage({ height = 5_000, viewport = 900, growth = 0 } = {}) {
  /** @type {number[]} */
  const visited = [];
  /** @type {number[]} */
  const pauses = [];
  let measured = height;

  return {
    visited,
    pauses,
    scroller: {
      viewportHeight: async () => viewport,
      documentHeight: async () => {
        const now = measured;
        measured += growth;
        return now;
      },
      scrollTo: async (/** @type {number} */ y) => void visited.push(y),
      pause: async (/** @type {number} */ ms) => void pauses.push(ms),
    },
  };
}

test("the walk visits every screen of the page, a viewport at a time", async () => {
  const page = fakePage({ height: 4_000, viewport: 900 });

  const { steps } = await scrollThroughPage(page.scroller, { stepMs: 5, settleMs: 5 });

  // 0, 900, 1800, 2700, 3600 — then the bottom, then home.
  assert.deepEqual(
    page.visited,
    [0, 900, 1800, 2700, 3600, 4000, 0],
    "a screen skipped is a screen of content that never mounts",
  );
  assert.equal(steps, 5);
});

test("the walk pauses on every screen, which is the whole point of it", async () => {
  const page = fakePage({ height: 2_700, viewport: 900 });

  await scrollThroughPage(page.scroller, { stepMs: 150, settleMs: 1_000 });

  assert.deepEqual(
    page.pauses,
    [150, 150, 150, 1_000, 1_000],
    "three steps at the step pause, then the bottom and the top at the settle",
  );
});

test("the walk ends at the top, not wherever it finished", async () => {
  const page = fakePage({ height: 9_000 });

  await scrollThroughPage(page.scroller, { stepMs: 1, settleMs: 1 });

  assert.equal(
    page.visited.at(-1),
    0,
    "a sticky header photographed mid-page is the wrong picture of the top of the page",
  );
});

test("the walk stops at the clip ceiling instead of touring the whole page", async () => {
  const page = fakePage({ height: 60_000, viewport: 900 });

  const { depth } = await scrollThroughPage(page.scroller, { stepMs: 1, settleMs: 1 });

  assert.ok(
    depth <= MAX_SHOT_PX + 900,
    `nothing past the ceiling survives the clip, so ${depth} is time spent on discarded pixels`,
  );
  assert.ok(Math.max(...page.visited) <= MAX_SHOT_PX + 900);
});

test("a page shorter than one screen is one stop and no wasted steps", async () => {
  const page = fakePage({ height: 400, viewport: 900 });

  const { steps } = await scrollThroughPage(page.scroller, { stepMs: 1, settleMs: 1 });

  assert.equal(steps, 1, "the top still has to be visited; the second screen does not exist");
  assert.deepEqual(page.visited, [0, 400, 0]);
});

test("a page that grows every time it is measured is still bounded", async () => {
  // An infinite feed: every measurement reports a taller document than the last,
  // so the ceiling is never reached and only the step guard can end this.
  const page = fakePage({ height: 5_000, viewport: 900, growth: 5_000 });

  const { steps } = await scrollThroughPage(page.scroller, {
    stepMs: 1,
    settleMs: 1,
    maxSteps: 12,
  });

  assert.equal(steps, 12, "the guard is the only thing standing between this and the deadline");
});

test("a page reporting a zero-height viewport falls back to the shot viewport", async () => {
  const page = fakePage({ height: 3_000, viewport: 0 });

  const { steps } = await scrollThroughPage(page.scroller, {
    stepMs: 1,
    settleMs: 1,
    maxSteps: 200,
  });

  // Stepping by 1px would take 200 steps to cover 200px and burn the deadline.
  assert.deepEqual(page.visited, [0, 900, 1800, 2700, 3000, 0]);
  assert.equal(steps, 4);
});

/* ---------------------------------------------------------------------------
   The bot wall

   VET-27 published a picture of a Vercel Security Checkpoint as Inspora. The
   page answered 200, rendered clean HTML, and settled, so nothing in the
   capture path had anything to complain about — and because nothing threw, the
   Firecrawl second chance in `apply.mjs`, which is precisely the tool for a
   wall that only appears in front of a CI runner, never got asked.

   The two checks below are the fix, and they are tested at the two seams they
   were built for: `matchChallenge` is pure, so the DOM signatures are checked
   against fixture probes instead of a browser, and `shotLooksBlank` reads an
   encoded image, so it can be pointed at the shots this repo has actually
   committed.
   --------------------------------------------------------------------------- */

/** An ordinary page's probe, which each test below overrides one field of. */
const ORDINARY = {
  title: "Otherkind — design studio",
  heading: "We make things for people who make things",
  text: "Otherkind is a two-person studio in Lisbon. We work on brand systems, editorial sites, and the occasional product. Selected work below; the rest is on request.",
  selectors: /** @type {string[]} */ ([]),
};

test("the checkpoint that shipped as Inspora is recognised by its title", () => {
  const hit = matchChallenge({ ...ORDINARY, title: "Vercel Security Checkpoint" });

  assert.equal(hit?.name, "Vercel security checkpoint");
});

test("the same wall is recognised by what it says, not only by its title", () => {
  // The sentence a reader would see. Some deployments title the page after the
  // site rather than after the checkpoint, so the body has to be enough.
  const hit = matchChallenge({
    title: "inspora",
    heading: "",
    text: "Failed to verify your browser. Please try again. Code 21",
    selectors: [],
  });

  assert.equal(hit?.name, "Vercel browser verification");
  assert.match(hit?.evidence ?? "", /failed to verify your browser/i);
});

test("Cloudflare's interstitial is caught by its title", () => {
  const hit = matchChallenge({ ...ORDINARY, title: "Just a moment..." });

  assert.equal(hit?.name, "Cloudflare interstitial");
});

test("Cloudflare's older wording is caught by its body", () => {
  const hit = matchChallenge({
    ...ORDINARY,
    title: "fortress.example",
    text: "Checking your browser before accessing fortress.example. This process is automatic.",
  });

  assert.equal(hit?.name, "Cloudflare browser check");
});

test("a Cloudflare challenge container is enough on its own", () => {
  // No title, no copy — the challenge has not painted yet. The container is
  // there from the first byte, and it exists on no page that is not one.
  const hit = matchChallenge({ title: "", heading: "", text: "", selectors: ["#challenge-stage"] });

  assert.equal(hit?.name, "Cloudflare challenge container");
  assert.equal(hit?.evidence, "#challenge-stage");
});

test("the vendor-neutral phrasing is caught whoever served it", () => {
  const hit = matchChallenge({
    ...ORDINARY,
    title: "fortress.example",
    text: "Verify you are human by completing the action below.",
  });

  assert.equal(hit?.name, "Human verification");
});

test("Akamai needs both halves of its denial, not just the title", () => {
  const title = "Access Denied";

  assert.equal(
    matchChallenge({ ...ORDINARY, title, text: "You do not have access to this project." }),
    null,
    "plenty of ordinary pages are titled Access Denied",
  );

  assert.equal(
    matchChallenge({
      ...ORDINARY,
      title,
      text: "You don't have permission to access this resource. Reference #18.7c2d1a3b",
    })?.name,
    "Akamai access denied",
  );
});

test("PerimeterX and DataDome are recognised by their own containers", () => {
  assert.equal(
    matchChallenge({ ...ORDINARY, selectors: ["#px-captcha"] })?.name,
    "PerimeterX challenge",
  );
  assert.equal(
    matchChallenge({ ...ORDINARY, selectors: ['iframe[src*="captcha-delivery.com"]'] })?.name,
    "DataDome challenge",
  );
});

test("a site documenting a long-press gesture is not a PerimeterX wall", () => {
  // This gallery is made of sites that document interactions. "Press and hold"
  // on its own is one of them; PerimeterX's whole sentence is not.
  assert.equal(
    matchChallenge({
      ...ORDINARY,
      text: "Press and hold anywhere on the canvas to drop a point. Drag to move it.",
    }),
    null,
  );

  assert.equal(
    matchChallenge({
      title: "fortress.example",
      heading: "",
      text: "Press & Hold to confirm you are a human (and not a bot).",
      selectors: [],
    })?.name,
    "PerimeterX press and hold",
  );
});

test("a captcha widget is a wall only when it is the entire page", () => {
  // The wall: a headline, a line of instruction, and the widget.
  assert.equal(
    matchChallenge({
      title: "fortress.example",
      heading: "",
      text: "Please complete the security check to continue.",
      selectors: [".h-captcha"],
    })?.name,
    "Captcha wall",
    "a page with nothing on it but a captcha is a captcha, not a page",
  );
});

test("a real page that talks about bot walls is still a real page", () => {
  // The false positive this whole list is written to avoid: a design engineer
  // writing up their edge setup, with a contact form at the bottom of it. It
  // names Cloudflare, names Vercel, names reCAPTCHA, and ships the widget.
  const hit = matchChallenge({
    title: "designengineer.tools",
    heading: "Notes on shipping at the edge",
    text: [
      "I moved this site off Vercel and onto Cloudflare Pages last spring, mostly for",
      "the cache rules. The one thing I miss is the preview deployment.",
      "Bot protection is the part nobody writes about: I ran a captcha on the contact",
      "form for a year before deciding that a honeypot field caught the same traffic",
      "for none of the cost. If you want to argue about it, the form is below, and yes",
      "it still has a reCAPTCHA on it while I finish migrating.",
      "Say hello. I read everything and answer most of it.",
    ].join(" "),
    selectors: [".g-recaptcha"],
  });

  assert.equal(hit, null, "mentioning a wall is not being one");
});

test("an ordinary page matches nothing at all", () => {
  assert.equal(matchChallenge(ORDINARY), null);
  assert.equal(matchChallenge({}), null, "an empty probe is not evidence of a wall");
});

test("every signature declares something to match on", () => {
  // A signature with no positive matcher would match every page in the gallery,
  // and it would do it silently — the run would just start failing everything.
  for (const signature of CHALLENGE_SIGNATURES) {
    const matchers = [signature.title, signature.heading, signature.text, signature.selectors];
    assert.ok(
      matchers.some((matcher) => matcher !== undefined),
      `${signature.name} matches on nothing, which means it matches on everything`,
    );
  }
});

test("the page is asked for exactly the selectors the signatures match on", () => {
  // These are two lists that have to stay one list: a selector named in a
  // signature but never queried is a signature that can never fire.
  const named = new Set(CHALLENGE_SIGNATURES.flatMap((signature) => signature.selectors ?? []));

  assert.deepEqual(
    [...named].sort(),
    [...CHALLENGE_SELECTORS].sort(),
    "a selector no probe asks for is a rule that does not exist",
  );
});

/* ---------------------------------------------------------------------------
   The image backstop
   --------------------------------------------------------------------------- */

/**
 * A near-white viewport with a small block of dark pixels in the middle of it,
 * which is what a challenge page is: one sentence on an empty screen.
 *
 * The default is measured against the real thing. The VET-27 Inspora capture
 * was 1440x900, mean channel value 254.6, variance 6.8 — about 0.1% of its
 * pixels were the sentence and the rest was background. These numbers reproduce
 * that shape rather than approximating "blank" by eye.
 *
 * @param {object} [options]
 * @param {number} [options.rows]  Height of the text block.
 * @param {number} [options.cols]  Width of the text block.
 * @returns {Promise<Buffer>}
 */
async function challengePng({ rows = 12, cols = 100 } = {}) {
  const width = 1440;
  const height = 900;
  const pixels = Buffer.alloc(width * height * 3, 250);

  for (let y = 440; y < 440 + rows; y += 1) {
    for (let x = 620; x < 620 + cols; x += 1) {
      const at = (y * width + x) * 3;
      pixels[at] = 40;
      pixels[at + 1] = 40;
      pixels[at + 2] = 40;
    }
  }

  return sharp(pixels, { raw: { width, height, channels: 3 } }).png().toBuffer();
}

/** The encode `finish()` performs, so a measurement here is a measurement there. */
async function asShot(/** @type {Buffer} */ png) {
  return await sharp(png)
    .resize({ width: 1440, fit: "inside", withoutEnlargement: true })
    .webp({ quality: 82, effort: 6 })
    .toBuffer();
}

test("a challenge page reads as blank on the numbers alone", async () => {
  const measurement = await measureShot(await asShot(await challengePng()));

  assert.equal(shotLooksBlank(measurement), true);
  assert.ok(measurement.variance < 12, `variance ${measurement.variance} should be under the line`);
  assert.ok(measurement.density < 0.01, `density ${measurement.density} should be under the line`);
});

test("an empty screen is blank even with nothing written on it at all", async () => {
  const white = await sharp({
    create: { width: 1440, height: 900, channels: 3, background: { r: 255, g: 255, b: 255 } },
  })
    .png()
    .toBuffer();

  assert.equal(shotLooksBlank(await measureShot(await asShot(white))), true);
});

test("flat but heavy, or light but varied, is a page and not a wall", async () => {
  // The `and` in `shotLooksBlank`, from both sides. A poster is one colour and
  // encodes big; a spare page is small and still has something in it.
  const varied = await measureShot(await asShot(await challengePng({ rows: 300, cols: 900 })));
  assert.equal(shotLooksBlank(varied), false, "a page with content on it is not blank");

  assert.equal(
    shotLooksBlank({ variance: 0, density: 0.4 }),
    false,
    "a flat image that costs 0.4 bytes a pixel is a photograph, not an empty screen",
  );
  assert.equal(
    shotLooksBlank({ variance: 90, density: 0.001 }),
    false,
    "a tiny image full of contrast is a spare page that compressed well",
  );
});

test("every shot this repo has committed survives the backstop", async () => {
  // The regression set, and the only honest one: these nine files are what the
  // gallery is made of, and they include the page most likely to be mistaken
  // for a wall — Bychudy is a real site that is one viewport tall. A threshold
  // edit that flags any of them is a threshold edit that breaks the pipeline.
  const files = (await readdir(DEFAULT_OUT_DIR)).filter((file) => file.endsWith(".webp"));

  assert.ok(files.length >= 6, "the regression set is the committed shots; there should be some");

  for (const file of files.sort()) {
    const measurement = await measureShot(await readFile(path.join(DEFAULT_OUT_DIR, file)));

    assert.equal(
      shotLooksBlank(measurement),
      false,
      `${file} is a published shot and reads as blank: variance ${measurement.variance.toFixed(1)}, density ${measurement.density.toFixed(4)}`,
    );
  }
});

test("a Firecrawl second chance that came back with a wall fails instead of publishing", async (t) => {
  // The one path with no DOM behind it. Firecrawl returns a PNG and nothing
  // else, so if it is served the same checkpoint the browser was, the picture
  // is the only evidence there is — and a wall photographed by a second service
  // is still a wall.
  const outDir = await scratch(t);

  await assert.rejects(
    captureWithFirecrawl({
      url: "https://www.inspora.design/",
      slug: "inspora",
      client: clientReturning(await challengePng()),
      outDir,
    }),
    (error) => {
      assert.ok(error instanceof CaptureBlockedError, "the failure is typed, not a bare Error");
      assert.equal(error.signature, "blank capture");
      assert.match(error.message, /^inspora captured as a blank page: 1440x900/);
      return true;
    },
  );

  await assert.rejects(
    access(path.join(outDir, "inspora.webp")),
    "nothing is written for a shot that did not earn it",
  );
});

test("transparency is composited onto white, not read as black", async () => {
  // A screenshot has no alpha, but a PNG with one must not turn a transparent
  // header into a bogus black swatch on its way through sharp.
  const png = await sharp({
    create: {
      width: 200,
      height: 200,
      channels: 4,
      background: { r: 220, g: 40, b: 40, alpha: 0 },
    },
  })
    .png()
    .toBuffer();

  assert.deepEqual(await extractPalette(png), ["#ffffff"]);
});
