/**
 * `extractPalette()`, pinned rule by rule.
 *
 * It is a pure function from pixels to hex, and every rule it enforces is a
 * judgement call that a future edit could quietly reverse — so what these tests
 * assert is the judgements, not the six strings any one page happens to produce.
 *
 * Every fixture is generated by sharp rather than committed, so the expected
 * colours are arithmetic rather than "whatever that PNG happens to contain".
 */

import assert from "node:assert/strict";
import test from "node:test";

import sharp from "sharp";

import { extractPalette } from "./palette.mjs";

/**
 * A PNG built from horizontal bands, top to bottom.
 *
 * @param {readonly { colour: [number, number, number], rows: number }[]} bands
 * @param {number} [width]
 * @returns {Promise<Buffer>}
 */
async function bandedPng(bands, width = 400) {
  const height = bands.reduce((total, band) => total + band.rows, 0);
  const pixels = Buffer.alloc(width * height * 3);

  let offset = 0;
  for (const { colour, rows } of bands) {
    for (let i = 0; i < rows * width; i += 1) {
      pixels[offset] = colour[0];
      pixels[offset + 1] = colour[1];
      pixels[offset + 2] = colour[2];
      offset += 3;
    }
  }

  return sharp(pixels, { raw: { width, height, channels: 3 } }).png().toBuffer();
}

const WHITE = /** @type {[number, number, number]} */ ([255, 255, 255]);
const BLACK = /** @type {[number, number, number]} */ ([0, 0, 0]);
const RED = /** @type {[number, number, number]} */ ([220, 40, 40]);
const BLUE = /** @type {[number, number, number]} */ ([40, 70, 220]);
const GREEN = /** @type {[number, number, number]} */ ([30, 160, 90]);

test("a flat colour comes back as one hex string", async () => {
  const png = await bandedPng([{ colour: RED, rows: 200 }]);

  assert.deepEqual(await extractPalette(png), ["#dc2828"]);
});

test("colours come back most-used first", async () => {
  const png = await bandedPng([
    { colour: RED, rows: 40 },
    { colour: BLUE, rows: 120 },
    { colour: GREEN, rows: 80 },
  ]);

  assert.deepEqual(await extractPalette(png), ["#2846dc", "#1ea05a", "#dc2828"]);
});

test("a white margin around a coloured page does not take a slot", async () => {
  // 10% white: present, but nowhere near the share an extreme has to own.
  const png = await bandedPng([
    { colour: WHITE, rows: 20 },
    { colour: RED, rows: 100 },
    { colour: BLUE, rows: 80 },
  ]);

  const palette = await extractPalette(png);

  assert.deepEqual(palette, ["#dc2828", "#2846dc"]);
});

test("a page that really is white says so", async () => {
  // 80% white. This is not a margin, it is the design.
  const png = await bandedPng([
    { colour: WHITE, rows: 160 },
    { colour: RED, rows: 40 },
  ]);

  assert.deepEqual(await extractPalette(png), ["#ffffff", "#dc2828"]);
});

test("a dark site keeps its black", async () => {
  const png = await bandedPng([
    { colour: BLACK, rows: 150 },
    { colour: GREEN, rows: 50 },
  ]);

  assert.deepEqual(await extractPalette(png), ["#000000", "#1ea05a"]);
});

test("two shades of the same colour collapse into one swatch", async () => {
  const near = /** @type {[number, number, number]} */ ([224, 46, 46]);
  const png = await bandedPng([
    { colour: RED, rows: 100 },
    { colour: near, rows: 100 },
  ]);

  const palette = await extractPalette(png);

  assert.equal(palette.length, 1, "a 4-per-channel difference is not a second colour");
});

test("the palette is capped, and the cap is a parameter", async () => {
  const png = await bandedPng([
    { colour: RED, rows: 60 },
    { colour: BLUE, rows: 50 },
    { colour: GREEN, rows: 40 },
    { colour: [200, 160, 20], rows: 30 },
    { colour: [120, 30, 190], rows: 20 },
    { colour: [20, 190, 200], rows: 10 },
    { colour: [190, 90, 160], rows: 8 },
    { colour: [90, 120, 30], rows: 6 },
  ]);

  assert.equal((await extractPalette(png)).length, 6, "the default is six");
  assert.equal((await extractPalette(png, { size: 3 })).length, 3);
});

test("every colour is a lowercase six-digit hex string", async () => {
  const png = await bandedPng([
    { colour: [5, 10, 250], rows: 100 },
    { colour: [250, 250, 5], rows: 100 },
  ]);

  for (const colour of await extractPalette(png)) {
    assert.match(colour, /^#[0-9a-f]{6}$/, `${colour} is not a parseable hex colour`);
  }
});

test("a page of nothing but near-white still yields a colour", async () => {
  // Everything here is filtered out by the extreme rule, so the fallback pass is
  // the only thing standing between this page and an empty palette.
  const png = await bandedPng([
    { colour: [252, 252, 252], rows: 100 },
    { colour: [246, 244, 240], rows: 30 },
  ]);

  const palette = await extractPalette(png);

  assert.ok(palette.length >= 1, "an empty palette is never the honest answer");
  assert.match(palette[0], /^#[0-9a-f]{6}$/);
});

test("transparency is composited onto white, not read as black", async () => {
  // A screenshot has no alpha, but a PNG with one must not turn a transparent
  // header into a bogus black swatch on its way through sharp.
  const png = await sharp({
    create: {
      width: 200,
      height: 200,
      channels: 4,
      background: { r: 220, g: 40, b: 40, alpha: 0 },
    },
  })
    .png()
    .toBuffer();

  assert.deepEqual(await extractPalette(png), ["#ffffff"]);
});
