/**
 * og.mjs — generates the raster brand assets: the one social card
 * (`public/og.png`) and the fallback icon (`public/favicon.ico`).
 *
 * This is a build *tool*, not a build *step*. It is run by hand (`npm run og`)
 * and its output is committed, for one reason: the card has to be set in Geist,
 * and Geist lives in `node_modules` as a woff2 rather than in any system font
 * directory. A rasteriser that resolves fonts through fontconfig (which is what
 * an SVG-to-PNG path gives you) would silently fall back to whatever sans the
 * build machine happens to have, and the card would render in the wrong
 * typeface on Vercel while looking correct locally. Silent visual drift on a
 * file nobody re-checks is the worst kind.
 *
 * So the text is laid out by the one thing on the machine that is guaranteed to
 * honour an `@font-face`: a browser. Playwright is already a devDependency
 * here (`pipeline/capture.mjs` uses it), and the fonts are inlined as data URIs
 * so the page has no filesystem or network dependency at all. Sharp then
 * normalises the buffer to a real 1200x630 PNG.
 *
 * The icon does not need any of that ceremony — it is two paths and no text —
 * but it lives here because it is the same mark, and a mark that is regenerated
 * by two different commands is a mark that ends up out of step with itself.
 *
 * Re-run this after changing the site mark, the wordmark, the palette, or the
 * section list.
 */

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

import { chromium } from "playwright";
import sharp from "sharp";

/** The Open Graph consensus size. Every consumer crops from this. */
const WIDTH = 1200;
const HEIGHT = 630;

/**
 * Light theme, because it is the `:root` default in `src/styles/global.css`
 * and therefore what the site "is" before a viewer's OS gets a vote. A card
 * cannot respond to `prefers-color-scheme`, so it has to pick one.
 */
const BG = "#ffffff";
const FG = "#171717";
/** `--faint`: the same 45% ink the site uses for metadata. */
const FAINT = "rgb(23 23 23 / 0.45)";
const HAIRLINE = "rgb(23 23 23 / 0.1)";

const OUT = fileURLToPath(new URL("../public/og.png", import.meta.url));

/**
 * `public/favicon.ico`, the fallback for anything that will not take an SVG
 * icon. A bare 32x32 PNG under an `.ico` name, which is what was already there
 * and what every browser that asks for the path actually accepts.
 */
const ICON_OUT = fileURLToPath(new URL("../public/favicon.ico", import.meta.url));
const ICON_SIZE = 32;

/**
 * The site mark, copied from `src/components/SiteMark.astro`.
 *
 * Copied rather than read off disk: this script renders a standalone page in a
 * throwaway browser, and importing an Astro component to get two paths out of
 * it would mean standing up a build for assets that are regenerated by hand.
 * The geometry lives in three files now (the component, `public/favicon.svg`,
 * and here) and they have to be changed together.
 *
 * `stroke` sits on the wrapper and the paths inherit it, so the same two paths
 * serve the card, where it resolves through `currentColor` to `FG`, and the
 * raster icon, where it has to be a literal.
 */
const MARK_SIZE = 72;
const TITLE_SIZE = 104;

/**
 * How far left the mark has to be pulled to sit in the wordmark's column.
 *
 * `0.096` is the glyph's own left bearing as a fraction of its size: on the
 * 16-unit grid the leftmost ink is the outer corner of the left foot, 1.537
 * units in. `0.04` is the `letter-spacing` pull the `h1` below already takes.
 */
const MARK_PULL = MARK_SIZE * 0.096 + TITLE_SIZE * 0.04;

const MARK_PATHS = `<path d="M2.2 14.1 L8 3.1 L13.8 14.1" fill="none" stroke-width="1.5" stroke-linejoin="miter" stroke-linecap="butt"/>
    <path d="M5.9 10.4 H10.1" fill="none" stroke-width="1.5" stroke-linecap="butt"/>`;

const MARK_SVG = `<svg class="mark" viewBox="0 0 16 16" stroke="currentColor" xmlns="http://www.w3.org/2000/svg">
    ${MARK_PATHS}
  </svg>`;

/** The same mark with the ink pinned, for the rasteriser. */
const ICON_SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" stroke="${FG}">
    ${MARK_PATHS}
  </svg>`;

/** Only the latin subset is needed: the card renders two fixed ASCII strings. */
const FONTS = {
  sans: "../node_modules/@fontsource-variable/geist/files/geist-latin-wght-normal.woff2",
  mono: "../node_modules/@fontsource-variable/geist-mono/files/geist-mono-latin-wght-normal.woff2",
};

/** @param {string} relative */
async function dataUri(relative) {
  const bytes = await readFile(fileURLToPath(new URL(relative, import.meta.url)));
  return `data:font/woff2;base64,${bytes.toString("base64")}`;
}

async function html() {
  const [sans, mono] = await Promise.all([dataUri(FONTS.sans), dataUri(FONTS.mono)]);

  return `<!doctype html>
<meta charset="utf-8">
<style>
  @font-face {
    font-family: "Geist";
    src: url("${sans}") format("woff2-variations");
    font-weight: 100 900;
  }
  @font-face {
    font-family: "Geist Mono";
    src: url("${mono}") format("woff2-variations");
    font-weight: 100 900;
  }

  * { margin: 0; padding: 0; box-sizing: border-box; }

  body {
    width: ${WIDTH}px;
    height: ${HEIGHT}px;
    background: ${BG};
    color: ${FG};
    font-family: "Geist", sans-serif;
    /* the site's own page padding, scaled to the card */
    padding: 96px;
    display: flex;
    flex-direction: column;
    justify-content: flex-end;
    -webkit-font-smoothing: antialiased;
  }

  h1 {
    font-size: ${TITLE_SIZE}px;
    font-weight: 600;
    /* matches the .hero__title optical treatment: tight tracking, and the
       stem pulled flush with the padding edge */
    letter-spacing: -0.045em;
    line-height: 1;
    margin-left: -0.04em;
  }

  .rule {
    height: 1px;
    background: ${HAIRLINE};
    margin: 40px 0 28px;
  }

  .sections {
    font-family: "Geist Mono", monospace;
    font-size: 30px;
    font-weight: 500;
    letter-spacing: 0.02em;
    color: ${FAINT};
  }

  /* The site mark, top left, where the page itself puts it. \`margin-bottom\`
     absorbs the free space, so the mark pins to the padding edge while the
     block below stays bottom-aligned.

     The left pull is two optical corrections at once: the glyph's own bearing
     (its leftmost ink is 1.537 of 16 units in) plus the same -0.04em the
     wordmark under it takes. Here the two sit in one column, so the mark's
     foot and the \`A\` of the wordmark have to land on the same vertical. */
  .mark {
    width: ${MARK_SIZE}px;
    height: ${MARK_SIZE}px;
    margin-bottom: auto;
    margin-left: -${MARK_PULL.toFixed(1)}px;
  }
</style>
<body>
  ${MARK_SVG}
  <h1>Aayush Manchanda</h1>
  <div class="rule"></div>
  <p class="sections">tools &middot; sites &middot; notes &middot; experiments</p>
</body>`;
}

async function main() {
  const browser = await chromium.launch();
  try {
    const page = await browser.newPage({
      viewport: { width: WIDTH, height: HEIGHT },
      deviceScaleFactor: 1,
    });

    await page.setContent(await html(), { waitUntil: "load" });
    // The faces are inlined, so this resolves immediately, but shooting before
    // it does would capture a frame of fallback metrics.
    await page.evaluate(() => document.fonts.ready);

    const shot = await page.screenshot({ type: "png" });

    // Sharp is the guarantee that what lands on disk is exactly 1200x630 and a
    // real PNG, whatever the browser handed back.
    const png = await sharp(shot)
      .resize(WIDTH, HEIGHT, { fit: "cover" })
      .png({ compressionLevel: 9 })
      .toBuffer();

    await writeFile(OUT, png);
    console.log(`og.png  ${WIDTH}x${HEIGHT}  ${(png.length / 1024).toFixed(1)}KB`);
  } finally {
    await browser.close();
  }

  // The raster icon. Transparent ground and dark ink, matching what was there
  // before: an icon with its own white plate is a white tile in a dark tab
  // strip, which is worse than an ink-coloured mark that goes quiet.
  const icon = await sharp(Buffer.from(ICON_SVG))
    .resize(ICON_SIZE, ICON_SIZE)
    .png({ compressionLevel: 9 })
    .toBuffer();

  await writeFile(ICON_OUT, icon);
  console.log(
    `favicon.ico  ${ICON_SIZE}x${ICON_SIZE}  ${(icon.length / 1024).toFixed(1)}KB`,
  );
}

await main();
