#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES — VET-274, the private /me library.  Run: bash scripts/private-setup-wizard.sh
# Values are typed hidden and set through CLIs, never printed; the summary names
# only what was set. Re-runnable: it overwrites in place; Enter keeps a saved value.
# ──────────────────────────────────────────────────────────────────────────

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"
# Outside the repo, so nothing in it can be committed by accident.
ENV_FILE="${PRIVATE_ENV_FILE:-$HOME/Downloads/Aayush/aayushmanchanda-private/.env}"
WRITTEN_VERCEL=(); WRITTEN_CONVEX=()
TOTAL_STAGES=7

# set_vercel NAME VALUE — production and preview, overwriting. Skips an empty value.
set_vercel() {
  local name="$1" value="$2" target
  [[ -n "$value" ]] || { SKIPPED+=("Vercel $name (left as it was: no value given)"); return; }
  for target in production preview; do
    if printf '%s' "$value" | vercel env add "$name" "$target" --force --yes >/dev/null 2>&1; then
      WRITTEN_VERCEL+=("$name($target)"); printf '  %s✓ set%s Vercel %s (%s)\n' "$GREEN" "$RESET" "$name" "$target"
    else
      SKIPPED+=("Vercel $name ($target): vercel env add $name $target --force"); warn "could not set Vercel $name ($target)"
    fi
  done
}

# set_convex NAME VALUE [--prod] — value piped on stdin, never on the command line.
set_convex() {
  local name="$1" value="$2" flag="${3:-}" label="dev"
  [[ "$flag" == "--prod" ]] && label="prod"
  if printf '%s' "$value" | npx convex env set "$name" $flag >/dev/null 2>&1; then
    WRITTEN_CONVEX+=("$name($label)"); printf '  %s✓ set%s Convex %s (%s)\n' "$GREEN" "$RESET" "$name" "$label"
  else
    SKIPPED+=("Convex $name ($label): npx convex env set $name $flag"); warn "could not set Convex $name ($label)"
  fi
}

banner "Private library setup (VET-274)"
stage "Check the tools"
missing=0
for tool in vercel gh npx openssl; do
  if command -v "$tool" >/dev/null 2>&1; then say "✓ $tool"; else warn "$tool is not on PATH"; missing=1; fi
done
[[ -f .vercel/project.json ]] || { warn "this checkout is not linked to Vercel: run  vercel link"; missing=1; }
grep -q '^CONVEX_DEPLOYMENT=' .env.local 2>/dev/null || {
  warn "this checkout is not linked to Convex. Run:"
  note "npx convex dev --once --configure existing --team aayush-personal --project aayushmanchanda-private"
  missing=1
}
gh auth status >/dev/null 2>&1 || warn "gh is not logged in; GitHub secrets will be listed as to-do at the end"
(( missing == 0 )) || { warn "fix the above, then re-run"; exit 1; }
mkdir -p "$(dirname "$ENV_FILE")" && touch "$ENV_FILE" && chmod 600 "$ENV_FILE"
note "Local values go to $ENV_FILE (outside the repo, mode 600)."
pause "Press Enter to continue."
stage "Clerk keys"
open_url "https://dashboard.clerk.com"
step "Open the aayushmanchanda.com application (the development instance)."
step "Configure → API keys. Copy the Publishable key (pk_test_…)."
ask_secret PUBLIC_CLERK_PUBLISHABLE_KEY "Paste the publishable key (hidden):"
step "Copy the Secret key (sk_test_…) from the same page."
ask_secret CLERK_SECRET_KEY "Paste the secret key (hidden):"
step "Configure → Sessions → Customize session token. Add this claim and save, so Convex can check your email:"
note '  "email": "{{user.primary_email_address}}"'
pause "Press Enter once it is saved."
stage "Convex production values"
open_url "https://dashboard.convex.dev/t/aayush-personal/aayushmanchanda-private"
step "Switch the deployment picker (top left) to Production."
step "Settings → URL & Deploy Key. The deploy key named \"vercel\" is the one you already made."
ask_secret CONVEX_DEPLOY_KEY "Paste the \"vercel\" production deploy key (hidden, Enter skips):"
step "Copy the Deployment URL (https://…convex.cloud)."
ask_secret PUBLIC_CONVEX_URL "Paste the Cloud URL (hidden):"
step "Copy the HTTP Actions URL (https://…convex.site)."
ask_secret PROD_CONVEX_SITE_URL "Paste the HTTP Actions URL (hidden):"
stage "Who is allowed in"
say "The one email address that may open /me. Everyone else gets a 404 after signing in."
ask_secret ALLOWED_EMAIL "Your email (hidden):"
existing_secret=$(_existing INGEST_SECRET || true)
INGEST_SECRET="${existing_secret:-$(openssl rand -hex 32)}"
note "INGEST_SECRET: ${existing_secret:+kept the one already saved}${existing_secret:-generated a new one with openssl}."
for key in PUBLIC_CLERK_PUBLISHABLE_KEY CLERK_SECRET_KEY PUBLIC_CONVEX_URL PROD_CONVEX_SITE_URL ALLOWED_EMAIL; do
  [[ -n "${!key}" ]] || { warn "$key is empty. Re-run and paste it."; exit 1; }
done
for key in PUBLIC_CLERK_PUBLISHABLE_KEY CLERK_SECRET_KEY PUBLIC_CONVEX_URL PROD_CONVEX_SITE_URL ALLOWED_EMAIL INGEST_SECRET; do
  write_env "$key" "${!key}"
done
stage "Vercel environment variables"
say "Sets five variables on the Vercel project for production and preview, overwriting."
confirm "Set them now?" && {
  set_vercel PUBLIC_CLERK_PUBLISHABLE_KEY "$PUBLIC_CLERK_PUBLISHABLE_KEY"
  set_vercel CLERK_SECRET_KEY "$CLERK_SECRET_KEY"
  set_vercel CONVEX_DEPLOY_KEY "$CONVEX_DEPLOY_KEY"
  set_vercel PUBLIC_CONVEX_URL "$PUBLIC_CONVEX_URL"
  set_vercel ALLOWED_EMAIL "$ALLOWED_EMAIL"
}
pause "Press Enter to continue."
stage "Convex environment variables"
say "ALLOWED_EMAIL and INGEST_SECRET on the production and the dev deployment."
confirm "Set them now?" && {
  set_convex ALLOWED_EMAIL "$ALLOWED_EMAIL" --prod
  set_convex INGEST_SECRET "$INGEST_SECRET" --prod
  set_convex ALLOWED_EMAIL "$ALLOWED_EMAIL"
  set_convex INGEST_SECRET "$INGEST_SECRET"
}
pause "Press Enter to continue."
stage "GitHub secrets for the publish cron"
say "The cron posts new Internal/* raindrops to the production /import endpoint."
confirm "Set INGEST_SECRET and CONVEX_SITE_URL now?" && {
  set_secret INGEST_SECRET "$INGEST_SECRET"
  set_secret CONVEX_SITE_URL "$PROD_CONVEX_SITE_URL"
}
pause "Press Enter to finish."
finish
(( ${#WRITTEN_VERCEL[@]} )) && note "set on Vercel: ${WRITTEN_VERCEL[*]}"
(( ${#WRITTEN_CONVEX[@]} )) && note "set on Convex: ${WRITTEN_CONVEX[*]}"
printf '\n'
note "Next: push a production deploy (merge the PR), then import the archive:"
note "  node scripts/private-import.mjs --prod"
